@include('input', ['input' => 'about'])

<img class="rounded-full w-24 h-24" src="{{ asset('img/me.jpg') }}" alt="Picture of me">

<p class="mt-8">My name is John<span class="text-red-400">,</span> I<span class="text-red-400">'</span>m 34<span class="text-red-400">,</span> and I’ve been building on the web since I was 14<span class="text-red-400">.</span> Like many others<span class="text-red-400">,</span> I started out with Microsoft Frontpage and a boy<span class="text-red-400">'</span>s dream of making a web page with links to all my favorite Quake 2 skins<span class="text-red-400">.</span> Naturally<span class="text-red-400">,</span> I had so much fun doing it that it remained a side hobby for about a decade<span class="text-red-400">.</span> During that time I continued learning more about my new craft from articles<span class="text-red-400">,</span> books<span class="text-red-400">,</span> youtube<span class="text-red-400">,</span> podcasts<span class="text-red-400">,</span> and whatever else I could get my hands on<span class="text-red-400">.</span></p>

{{-- <p class="mt-8">Around 2009<span class="text-red-400">,</span> I got my first job as a “real” designer/developer<span class="text-red-400">.</span> Since then<span class="text-red-400">,</span> I<span class="text-red-400">'</span>ve worked my way from making simple brochure-style websites with basic HTML/CSS sprinkled with a little bit of jQuery and PHP<span class="text-red-400">,</span> to small applications with Codeigniter and jQuery/Mootools<span class="text-red-400">,</span> to bigger applications with Laravel and React/Vue<span class="text-red-400">.</span></p> --}}

<p class="mt-8">Today<span class="text-red-400">,</span> I am part of a small remote software company in the healthcare space<span class="text-red-400">.</span> There I envision<span class="text-red-400">,</span> present<span class="text-red-400">,</span> plan<span class="text-red-400">,</span> design<span class="text-red-400">,</span> and then build about half of the pieces of our SAAS product<span class="text-red-400">.</span> We build/sell a “patient experience platform”<span class="text-red-400">,</span> which is really just marketing-speak for surveys<span class="text-red-400">.</span> There’s more to it than that of course with EMR integration<span class="text-red-400">,</span> heathcare compliance<span class="text-red-400">,</span> incident management<span class="text-red-400">,</span> etc<span class="text-red-400">.</span> But you get the idea<span class="text-red-400">.</span></p>

<p class="mt-8">In my off-hours<span class="text-red-400">,</span> I travel full-time with my family of 5 in our RV<span class="text-red-400">.</span> We’ve spent the last year and a half exploring and learning about our beautiful nation<span class="text-red-400">.</span> If you<span class="text-red-400">'</span>d like to keep up with our journey<span class="text-red-400">,</span> check out our <a class="text-blue-400 hover:text-blue-500" href="https://www.instagram.com/freemansboldlygo" target="_blank">Instagram</a><span class="text-red-400">.</span></p>
