services:
  # server:
  #   build:
  #     context: .
  #     target: final
  #   environment:
  #     DATABASE_URL: '${DATABASE_URL}'
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     db:
  #       condition: service_healthy
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 5432:5432
    # expose:
    #   - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
volumes:
  db-data:
    driver: local
