version: '3'

services:
  app:
    build:
      context: .
      target: final
    environment:
      DATABASE_URL: '${DATABASE_URL}'
      MAIL_HOST: '${MAIL_HOST}'
      MAIL_PORT: '${MAIL_PORT}'
      MAIL_USERNAME: '${MAIL_USERNAME}'
      MAIL_PASSWORD: '${MAIL_PASSWORD}'
      MAIL_FROM_ADDRESS: '${MAIL_FROM_ADDRESS}'
      MAIL_FROM_NAME: '${MAIL_FROM_NAME}'
    ports:
      - 80:80
    labels:
      - "traefik.http.routers.server.rule=PathPrefix(`/`)"
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    extends:
      file: compose.yaml
      service: db
    restart: always
volumes:
  db-data:
    driver: local

