version: '3'

services:
  reverse-proxy:
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    build:
      context: .
      target: final
    environment:
      DATABASE_URL: '${DATABASE_URL}'
      MAIL_HOST: '${MAIL_HOST}'
      MAIL_PORT: '${MAIL_PORT}'
      MAIL_USERNAME: '${MAIL_USERNAME}'
      MAIL_PASSWORD: '${MAIL_PASSWORD}'
      MAIL_FROM_ADDRESS: '${MAIL_FROM_ADDRESS}'
      MAIL_FROM_NAME: '${MAIL_FROM_NAME}'
    ports:
      - 3000:3000
    labels:
      - "traefik.http.routers.server.rule=PathPrefix(`/`)"
    depends_on:
      db:
        condition: service_healthy
  db:
    extends:
      file: compose.yaml
      service: db
    restart: always
volumes:
  db-data:
    driver: local

